name: rag
channels:
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.9.19
  - flask=3.0.2
  - openai=1.14.3
  - python-dotenv=1.0.1
  - langdetect=1.0.9
  - langchain-text-splitters=0.0.1
  - ruff=0.3.4
  - toml=0.10.2
  - scikit-learn=1.4.0
  - numpy=1.26.4
  - dill=0.3.8
  - poppler=24.04.0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.7.0
      - cachetools==5.3.3
      - camelot-py==0.11.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cobble==0.1.3
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.2.0
      - cryptography==42.0.2
      - cycler==0.12.1
      - dataclasses-json==0.6.4
      - dataclasses-json-speakeasy==0.5.11
      - debugpy==1.8.1
      - decorator==5.1.1
      - deep-translator==1.11.4
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.8
      - distro==1.9.0
      - doc2docx==0.2.4
      - docx2txt==0.8
      - effdet==0.4.1
      - emoji==2.10.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - faiss-cpu==1.8.0
      - fake-useragent==1.5.1
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - filetype==1.2.0
      - flask==3.0.2
      - flatbuffers==23.5.26
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - fuzzywuzzy==0.18.0
      - google-api-core==2.18.0
      - google-api-python-client==2.123.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.4
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iopath==0.1.10
      - ipykernel==6.29.3
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.24
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - langchain==0.1.13
      - langchain-community==0.0.29
      - langchain-core==0.1.42
      - langchain-openai==0.1.1
      - langchain-text-splitters==0.0.1
      - langdetect==1.0.9
      - langsmith==0.1.47
      - layoutparser==0.3.4
      - loguru==0.6.0
      - lxml==5.1.0
      - mammoth==1.7.1
      - markdown==3.5.2
      - markdown2==2.4.13
      - markdownify==0.12.1
      - markupsafe==2.1.5
      - marshmallow==3.20.2
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - msg-parser==1.2.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nltk==3.8.1
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - olefile==0.47
      - omegaconf==2.3.0
      - onnx==1.15.0
      - onnxruntime==1.15.1
      - openai==1.14.3
      - opencv-python==4.8.0.76
      - openpyxl==3.1.2
      - orjson==3.10.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pdf2image==1.17.0
      - pdfminer-six==20221105
      - pdfplumber==0.10.4
      - pexpect==4.9.0
      - pikepdf==8.11.0
      - pillow==10.2.0
      - pillow-heif==0.15.0
      - platformdirs==4.2.0
      - portalocker==2.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - proto-plus==1.23.0
      - protobuf==4.23.4
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyclipper==1.3.0.post5
      - pycocotools==2.0.7
      - pycparser==2.21
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - pypandoc==1.12
      - pyparsing==3.0.9
      - pypdf==4.0.1
      - pypdfium2==4.27.0
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-docx==1.1.0
      - python-dotenv==1.0.1
      - python-iso639==2024.2.7
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-pptx==0.6.23
      - python_Levenshtein==0.23.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rapidfuzz==3.6.1
      - rapidocr-onnxruntime==1.3.15
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - ruff==0.3.4
      - safetensors==0.3.2
      - scikit-learn==1.4.0
      - scipy==1.10.1
      - send2trash==1.8.2
      - shapely==2.0.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.28
      - sqllex==0.3.0.post2
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tiktoken==0.6.0
      - timm==0.9.12
      - tinycss2==1.2.1
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.2.0
      - torchvision==0.17.0
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.37.1
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - unstructured==0.12.6
      - unstructured-client==0.18.0
      - unstructured-inference==0.7.23
      - unstructured-pytesseract==0.3.12
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==1.26.18
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xlrd==2.0.1
      - xlsxwriter==3.1.9
      - yarl==1.9.4
      - zipp==3.17.0
