name: Install Anaconda Environment

on:
  push:
    branches:
      - '**'       
      - '!master'

jobs:
  build:
    name: Run anaconda on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda env create -f environments/conda.yml
          conda env list 
          conda list